// Generated by https://quicktype.io

export interface Hero {
  id: number;
  nombres: string;
  //publisher:        Publisher;
  apellidos: string;
  pais: string;
  cedula: string;
  celular: string;
  alt_img?: string;
}

/* export enum Publisher {
  DCComics = "DC Comics",
  MarvelComics = "Marvel Comics",
} */
